spring:
    jpa:
        database: H2
        generate-ddl: true
        show-sql: true
    h2:
        console:
            enabled: true

datasource:
    article:
        url: jdbc:h2:mem:article
        username: sa
    user:
        url: jdbc:h2:mem:user
        username: sa

## Default
#spring:
#    datasource:
#        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#        username: sa
#        password: 
#        driverClassName: org.h2.Driver